name: Build & Depoly

on:
  push:
    branches:
      - develop
env:
   CI: false

jobs:
  build:
     name:Build
     runs-on: ubuntu-latest
     
steps:
	- name: Checkout repo 
	  uses: actions/setup-node@v2

	- name: Setup Node
	  uses: actions/setup-node@v1
	  with:
	     node-version:18

	- name: Install dependencies
	  uses: bahmutov/npm-install@v1

	- name: Builad project 
	  run: npm run build

	- name: Upload production-ready buld files 
	  uses: actions/upload-artifact@v2
	  with:
	     name: production-files
	     path: ./build

  deploy:
      name:Deploy
      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/develop'

      steps:
	- name: Download artifact
	  uses: actions/download-artifact@v2
	  with:
	     name: production-files
	     path: ./build

	- name: Deploy to Github pages 
	  uses: peaceiris/actions-gh-pages@v3
	  with: 
	    github_token: ${{ secrets.TOKEN }}
	    publish_dir: ./build
	
